name: Release

on: [ push ]

jobs:
  release:
    needs: build
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # install dependencies and run semantic-release
      - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
      - run: semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
